import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/favicon.ico" />
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="google-site-verification"
          content="nMmumpLhU6oMBkvrqzGJEWcvC_btwJ4okjgahmTxBxk"
        />
        <meta
          name="description"
          content="Experienced freelance full-stack developer specializing in React.js, Next.js, Express.js, Node.js, MySQL, Sequelize.js, and TypeScript. Available for hire to build scalable and efficient web applications. Contact now to discuss your project requirements. Hire Full Stack Developer today!"
        />
        <meta
          name="keywords"
          content="freelance full stack developer, full stack developer for hire, react.js developer, next.js developer, node.js developer, express.js developer, mysql developer, sequelize.js developer, typescript developer, hire full stack developer, hire developer, freelance developer"
        />
        <meta name="author" content="Thareq Muhammad Azani" />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100;0,9..40,200;0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;0,9..40,800;0,9..40,900;0,9..40,1000;1,9..40,100;1,9..40,1000&display=swap"
          rel="stylesheet"
        />
        <title>Thareq Muhammad Azani - Web Developer</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
